version: "3"
services:
  web:
    container_name: nodeapp
    restart:  always
    build: .
    ports: 
        - "5000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    container_name: mongo_db
    image: mongo
    ports: 
        - "27018:27017"
   
